"""init

Revision ID: 5c5924fd9221
Revises: edc0c4f99ff0
Create Date: 2021-06-27 01:46:33.253240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5924fd9221'
down_revision = 'edc0c4f99ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
