"""init

Revision ID: 69c65aeaf1e0
Revises: 64b1e3ac70b0
Create Date: 2021-06-26 17:36:41.255808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c65aeaf1e0'
down_revision = '64b1e3ac70b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ent_results', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ent_results', 'category')
    # ### end Alembic commands ###
