"""init

Revision ID: d5702b5f65cc
Revises: 5c5924fd9221
Create Date: 2021-06-27 01:51:08.400079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5702b5f65cc'
down_revision = '5c5924fd9221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aet_results',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('first_exam_link', sa.String(length=255), nullable=True),
    sa.Column('second_exam_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('schedule', sa.Column('descr', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'descr')
    op.drop_table('aet_results')
    # ### end Alembic commands ###
